- CHANGELOG.md
- package.json
This increases the version to 1.0.0, first github release.
> Release 1.0.0 on Github

- .github/workflows/codespell.yml
As discussed in #6, tests are failing at https://github.com/cclauss/farmerconnect-ui/actions
> Error: ./CHANGELOG.md:12: storys ==> stories, storeys
> GitHub Action to find typos

- README.md
- src/components/Checkbox/styles.ts
This commit updates the readme to reflect the project.
I purposefully left it without creating a new version because it doesn't change functionality.
> Add readme

- CHANGELOG.md
- package.json
This PR fixes the package name in order to publish it under "farmerconnect" org no npmjs.org
> Fix package name

- CHANGELOG.md
- package.json
- src/components/Table/index.stories.tsx
- src/components/Table/index.tsx
- src/components/Table/interfaces.ts
- src/components/Table/styles.ts
- src/components/Theme.ts
- Table component changes
- Default font-weight updated to 500
- Slim prop added
- Default theme added
> Slim prop and theme added to table component

- CHANGELOG.md
- package.json
- src/components/DropdownSelect/index.stories.tsx
- src/components/DropdownSelect/index.tsx
- Hiding drag and drop action when search is active on dropdownSelect component
> Supress dnd when search is active on dropdownSelect

- CHANGELOG.md
- package.json
- src/components/FilterSelect/index.tsx
Clear input when a list element is not selected
> Fixed selectedItem prop in FilterSelect

- CHANGELOG.md
- package.json
- src/components/TextInput/index.tsx
- src/components/TextInput/interfaces.ts
- Added a optional props on TextInput component to receive a function to validate
> TextInput validate function

- CHANGELOG.md
- package.json
- src/components/EditableLabel/index.stories.tsx
- src/components/EditableLabel/index.test.tsx
- src/components/EditableLabel/index.tsx
- src/components/EditableLabel/interfaces.ts
- src/components/EditableLabel/styles.ts
> added: validation function prop

- CHANGELOG.md
- package.json
- src/components/Card/index.tsx
- src/components/Card/interfaces.ts
- src/components/Card/styles.ts
Added open/close event in Card component and new font size for default card component title
> Added open/close event in Card component and new font size for default card component title

- azure-pipelines.yml
Added Snyk scan to the Azure pipeline
> Snyk integration

- CHANGELOG.md
- package.json
- src/components/LabelSwitch/index.stories.tsx
- src/components/LabelSwitch/index.test.tsx
- src/components/LabelSwitch/index.tsx
- src/components/LabelSwitch/styles.ts
- Included labelSwitch component
> Included labelSwitch

- CHANGELOG.md
- package.json
- src/components/Select/index.tsx
- src/components/SingleSelect/index.tsx
- src/components/SingleSelect/styles.tsx
- src/components/SmallSelect/index.tsx
- Select now close when single and keep open when multi
- Fix filters width on singleSelect component
> Fix select

- src/components/Colors/index.stories.tsx
- src/components/Colors/index.tsx
- src/components/Colors/styles.stories.ts
- src/components/Colors/styles.ts
- src/components/Theme.ts
- src/styles/colors.ts
Add colors to theme file.
Add color swatches stories for colors.
> feat(colors): add color swatches

- CHANGELOG.md
- package.json
- src/components/TextArea/styles.tsx
The textarea component was cropping the content. Custom scrollbar style added.
> Textarea multiline overflow bug fix

- CHANGELOG.md
- package.json
- src/components/Checkbox/index.stories.tsx
- src/components/Checkbox/index.tsx
- src/components/Checkbox/styles.ts
- src/components/CustomButton/styles.ts
- src/components/Radio/index.stories.tsx
- src/components/Radio/index.tsx
- src/components/Radio/styles.ts
- src/components/Tabs/index.stories.tsx
- src/components/Tabs/styles.ts
- Added disabled style to Radio
- Fixed Tab's current tab highlight
> - Added disabled style to Checkbox

- CHANGELOG.md
- package.json
- src/components/SearchInput/index.stories.tsx
- src/components/SearchInput/index.test.tsx
- src/components/SearchInput/index.tsx
- src/components/SearchInput/interfaces.ts
- src/components/SearchInput/styles.tsx
- src/components/SearchInput/utils.ts
- src/index.tsx
Adding a search input component that accepts an `onSearch` function which could implement any kind of search.
A couple of screenshots:
Still **TODO**:
- Add tests to the component
- Add a dropdown section to show results in case an autosuggestion search is performed
> Add SearchInput component

- CHANGELOG.md
- package.json
- src/components/Icons/Options/index.tsx
- src/components/Icons/index.ts
> Options icon added

- CHANGELOG.md
- package.json
> Changing version to 3.1.1

- CHANGELOG.md
- package.json
- src/components/SearchInput/styles.tsx
> Refactoring in the SearchInput component

- CHANGELOG.md
- package.json
- src/components/TextArea/index.stories.tsx
- src/components/TextArea/styles.tsx
> TextArea disabled style fix

- CHANGELOG.md
- package.json
- src/components/Modal/index.tsx
- src/components/Modal/styles.ts
changed overlay styling so the modal dialog doen't blend with background when loading overlay is displayed
> fixed: modal loading layout

- CHANGELOG.md
- package.json
- src/components/FileUpload/index.tsx
- src/components/FileUpload/interfaces.ts
- yarn.lock
> Adding properties to send the translated texts to the file upload component

- CHANGELOG.md
- package.json
- src/components/DatePicker/index.test.tsx
- src/components/DatePicker/index.tsx
- src/components/DatePicker/styles.ts
> Fixed user should also be able to click calendar icon to open the date picker
